### ISSUE TITLE
Error running Postman tests

### ISSUE THREAD

**Issue by kortiz75** [carlowahlstedt/NewmanPostman_VSTS_Task#53]
When trying to run Postman tests in Azure DevOps Pipeline, received this error:
`[command]/home/vsts/work/node_modules/newman/bin/newman.js run /home/vsts/work/r1/a/_[Build] Accounting/service/Accounting API Testing.postman_collection.json -n 3 -e /home/vsts/work/r1/a`

`error: EISDIR: illegal operation on a directory, read`

`##[error]The process '/home/vsts/work/node_modules/newman/bin/newman.js' failed with exit code 1`

This code was working fine before just now. I notice your last commit was an hour ago. Could be related...

**Comment by carlowahlstedt** [comment]
You are correct! I was literally in the middle of testing and deploying when my internet went out!

I'm working to correct it now. Sorry for any issues.

**Comment by carlowahlstedt** [comment]
Ok, this should be working again.

@sebcaps found an issue with your changes but we hadn't noticed because the release pipeline versioning was messed up. It was updating v1 of the task instead of v3. I left v1 broken and fixed v3. The change that broke this was the task variable rename from environment to environmentFile. I put it back and it picked it back up. Looks like renaming task variables isn't backward compatible (which make sense). Live and learn. 

Thanks for submitting the issue @kortiz75 and being patient for the fix. Can you please close this when you confirm it's working for you again?

**Comment by kortiz75** [comment]
Unfortunately, I'm still getting the same error. I tried running it a few times.

**Comment by carlowahlstedt** [comment]
Can you verify the Version for me?
![image](https://user-images.githubusercontent.com/2687687/53120235-62d69880-351f-11e9-9e6b-35d3d8ed65cd.png)

**Comment by kortiz75** [comment]
![image](https://user-images.githubusercontent.com/13276210/53127558-bdc4bb80-3530-11e9-8e6b-178fe5406e44.png)

**Comment by carlowahlstedt** [comment]
Can you verify your environment source is set like you'd expect (file I would assume). And that the file is what would expect as well?

**Comment by kortiz75** [comment]
Looks like the environment file was getting deleted for some reason. I added the file again, and it's working now. Thank you!
